# Network parameters configuration
run_DQlearning: False
run_surr_opt: True
run_adaptive_contrast_tao: False
trainingFixed: True # True, False
num_replications: 4 # 4, 9, 30, 100

batch_size: 200 # 150, 200 Batch size calculated as a proportion of sample size
optimizer_lr: 0.007 #0.07 #0.007
n_epoch: 120 #  # 60 # 90, 150  # Number of training epochs

phi_ensemble: False # if this is true keep ensemble_count to 5
ensemble_count: 1 # 5 

# phi_ensemble: True # if this is true keep ensemble_count to 5
# ensemble_count: 5 # 5

activation_function: elu # elu, none, relu, sigmoid, tanh, leakyrelu,  # # CHANGEd INSIDE
num_layers: 4 # 4 
hidden_dim_stage1: 40  # 40, 
hidden_dim_stage2: 40  # 40, 
dropout_rate: 0.4  # 0.4 Dropout rate to prevent overfitting
gradient_clipping: True # True, False 
add_ll_batch_norm: True 

# 159 for DQL and set param_grid = {} 
# num_layers: 1 
# hidden_dim_stage1: 4  
# hidden_dim_stage2: 4  
# dropout_rate: 0.0  # 0.4 Dropout rate to prevent overfitting 
# gradient_clipping: False # True, False 
# add_ll_batch_norm: False 

f_model: "model_used"  # DQlearning, surr_opt, tao; will update this automatically later
device: None  # Computation device, dynamically set to 'cuda' if GPU is available
sample_size: 17368   # 3000  # Number of samples to be used -> including both stages total 36926 data points

training_validation_prop: 0.8  # Proportion of data for training vs validation
num_networks: 2  # Number of parallel networks or models

output_dim_stage1: 1  # Output dimension for stage 1
output_dim_stage2: 1  # Output dimension for stage 2
optimizer_weight_decay: 0.001  # Weight decay (L2 regularization) helps prevent overfitting

use_scheduler: True # True, False
scheduler_type: reducelronplateau  # Type of learning rate scheduler, can be 'reducelronplateau', 'steplr', or 'cosineannealing'
scheduler_step_size: 30  # Step size for StepLR, defines the number of epochs before the next LR decay
scheduler_gamma: 0.8  # Decay rate for learning rate under StepLR

optimizer_type: adam  # 'adam' or 'rmsprop'

surrogate_num: 1  # Indicates the surrogate model configuration number
option_sur: 2  # Specifies the operational mode or variant of the surrogate model
contrast: 1
initializer: he  # He initialization method (Kaiming initialization)


dql_params:
  num_layers: 4
  hidden_dim_stage1: 64
  hidden_dim_stage2: 128
  activation_function: relu
  add_ll_batch_norm: True
  optimizer_lr: 0.01
  batch_size: 200 
  n_epoch: 120 
  gradient_clipping: True # True, False 
  add_ll_batch_norm: True 
  dropout_rate: 0.4  